# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=50)),
                ('market', models.CharField(blank=True, max_length=50)),
                ('asset_class', models.CharField(blank=True, choices=[('stock', 'Stock'), ('index', 'Index'), (None, '')], max_length=10)),
                ('investments', models.ManyToManyField(blank=True, null=True, through='portfolios.Allocation', to='portfolios.Investment')),
            ],
        ),
        migrations.AddField(
            model_name='historicprice',
            name='investment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.Investment'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset', to='portfolios.Investment'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='portfolios.Investment'),
        ),
    ]
