# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='stocks',
            field=models.ManyToManyField(to='portfolios.Stock'),
        ),
    ]
