# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 05:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_portfolio_stocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.RenameModel(
            old_name='Stock',
            new_name='Investment',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='stocks',
        ),
        migrations.AddField(
            model_name='allocation',
            name='investment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.Investment'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.Portfolio'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='investments',
            field=models.ManyToManyField(through='portfolios.Allocation', to='portfolios.Investment'),
        ),
    ]
