# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_auto_20160320_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
