# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0004_auto_20160320_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='asset_class',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='investment',
            name='market',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
