# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0005_auto_20160320_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='asset_class',
            field=models.CharField(blank=True, choices=[('stock', 'Stock'), ('index', 'Index'), (None, '')], max_length=10),
        ),
    ]
