# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0006_auto_20160320_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.DecimalField(decimal_places=2, max_digits=6)),
                ('high', models.DecimalField(decimal_places=2, max_digits=6)),
                ('low', models.DecimalField(decimal_places=2, max_digits=6)),
                ('close', models.DecimalField(decimal_places=2, max_digits=6)),
                ('adjusted_close', models.DecimalField(decimal_places=2, max_digits=6)),
                ('volume', models.PositiveIntegerField()),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.Investment')),
            ],
        ),
    ]
