# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0007_historicprices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricPrices',
            new_name='HistoricPrice',
        ),
    ]
