# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0009_auto_20160320_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='ticker',
            new_name='symbol',
        ),
    ]
